### ISSUE TITLE
Feedback/Idea: Use a specific library for dynamic objects.

### ISSUE THREAD

**Issue by drupol** [peridot-php/leo#29]
Hi,

I've discovered your library 3 weeks ago and a colleague included it for the test in [Atomium](https://github.com/ec-europa/atomium/pull/50), a Drupal theme project from the European Commission.
It was the first time I saw such a mechanism to extend classes and I really like it, congratulations, it's impressive.

I liked it so much that I've decided to make a small library that everyone could use and extend too.

You can find it here: https://github.com/drupol/DynamicObjects
It's 100% tested by PHPSpec.

Do you think that Leo might use it and so get rid of the DynamicObjectTrait.php in src/ ?

Let me know what you think.

Thanks!

**Comment by ezzatron** [comment]
@brianium would probably be the person who implemented the system you're talking about. Unfortunately I'm just a maintainer here, but I do think it's great that you found some inspiration here.

This repo has been pretty quiet for a while now, especially with the recent popularity of Kahlan, which is much more active, and fills much the same role as Peridot + Leo. At this point, basically only bugfixes are likely to get merged, sorry.

**Comment by drupol** [comment]
Ok ok!

I will have a look at Kahlan.

Thanks :-)
